version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - mailcatcher
  db:
    image: postgres:9
    ports:
      - "5432:5432"
    volumes:
      - ./tools/docker/cache_table.sql:/docker-entrypoint-initdb.d/cache_table.sql
    environment:
      - POSTGRES_DB=kairos
      - POSTGRES_USER=kairos
      - POSTGRES_PASSWORD=kairos
  phppgadmin:
    image: zhajor/docker-phppgadmin
    ports:
      - "8001:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "8002:1080"