# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 03:39
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_state_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True, verbose_name='is_new')),
            ],
            options={
                'verbose_name': 'candidacy',
                'verbose_name_plural': 'candidacies',
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'mandate',
                'verbose_name_plural': 'mandates',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='party',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='party',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='party',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='party',
            name='shortname_fr',
        ),
        migrations.RemoveField(
            model_name='party',
            name='shortname_it',
        ),
        migrations.RemoveField(
            model_name='party',
            name='shortname_nl',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='is_member_of_parliament',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_it',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_it',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_nl',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_nl',
        ),
        migrations.AlterField(
            model_name='party',
            name='background_color',
            field=colorfield.fields.ColorField(default='#3F51B5', max_length=18, verbose_name='background_color'),
        ),
        migrations.AlterField(
            model_name='party',
            name='font_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='font_color'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='politicians/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='state',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='sort'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mandate', verbose_name='mandate'),
        ),
        migrations.AddField(
            model_name='politician',
            name='candidacy',
            field=models.ManyToManyField(blank=True, to='core.Candidacy', verbose_name='candidacy'),
        ),
    ]
