# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190812_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
