# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190812_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=2, verbose_name='iso_code')),
            ],
        ),
        migrations.RemoveField(
            model_name='politician',
            name='state',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='politician',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Language', verbose_name='language'),
        ),
    ]
