# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190816_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
    ]
