# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-10 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190816_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='party',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='party',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='party',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='party',
            name='shortname_fr',
            field=models.CharField(max_length=10, null=True, verbose_name='shortname'),
        ),
        migrations.AddField(
            model_name='party',
            name='shortname_it',
            field=models.CharField(max_length=10, null=True, verbose_name='shortname'),
        ),
        migrations.AddField(
            model_name='party',
            name='shortname_nl',
            field=models.CharField(max_length=10, null=True, verbose_name='shortname'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description', blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description_it',
            field=models.TextField(null=True, verbose_name='description', blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description_nl',
            field=models.TextField(null=True, verbose_name='description', blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_fr',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_it',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_nl',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
